# Generated by Django 6.1 on 2026-09-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(help_text='The original long destination URL', max_length=2048)),
                ('short_code', models.CharField(db_index=True, help_text='Unique short code of at most 5 characters', max_length=5, unique=True)),
                ('url_hash', models.CharField(db_index=True, help_text='SHA-256 hash of original_url for fast deduplication lookup', max_length=64)),
                ('clicks_count', models.PositiveBigIntegerField(default=0, help_text='Total number of times this short link has been accessed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the short URL was created')),
                ('last_accessed_at', models.DateTimeField(blank=True, help_text='Timestamp of the most recent access/redirection', null=True)),
            ],
            options={
                'verbose_name': 'Shortened URL',
                'verbose_name_plural': 'Shortened URLs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['short_code'], name='idx_short_code'), models.Index(fields=['url_hash'], name='idx_url_hash')],
            },
        ),
    ]
